use cgmath::Matrix4;
use fontdue::Font;
use glium::index::{NoIndices, PrimitiveType};
use glium::{
    Display, Surface, implement_vertex,
    texture::{MipmapsOption, RawImage2d, Texture2d},
    uniform,
};
use glium::{Frame, Program};
use glutin::surface::WindowSurface;
use std::collections::HashMap;
#[derive(Clone)]
pub struct GlyphInfo {
    pub uv_rect: [f32; 4],
    pub size_px: [f32; 2],
    pub advance: f32,
    pub bearing: [f32; 2],
}
pub struct FontAtlas {
    pub texture: Texture2d,
    pub glyphs: HashMap<char, GlyphInfo>,
    pub base_px_size: f32,
    pub atlas_px_size: (u32, u32),
}
impl FontAtlas {
    pub fn new(
        display: &Display<WindowSurface>,
        font_bytes: &[u8],
        base_px_size: f32,
        chars: &[char],
    ) -> Self {
        let font = Font::from_bytes(font_bytes, fontdue::FontSettings::default())
            .expect("failed to load font bytes");
        let mut glyph_entries = Vec::<(char, Vec<u8>, usize, usize, f32, f32, f32)>::new();
        let mut max_w: usize = 1;
        let mut max_h: usize = 1;
        for &c in chars {
            let (metrics, bitmap) = font.rasterize(c, base_px_size);
            let w = metrics.width.max(1);
            let h = metrics.height.max(1);
            let bmp = if bitmap.is_empty() {
                vec![0u8; w * h]
            } else if bitmap.len() != (w * h) {
                let mut b = vec![0u8; w * h];
                let min_len = bitmap.len().min(w * h);
                b[..min_len].copy_from_slice(&bitmap[..min_len]);
                b
            } else {
                bitmap
            };
            max_w = max_w.max(w);
            max_h = max_h.max(h);
            let bx = metrics.xmin as f32;
            let by = metrics.ymin as f32 + metrics.height as f32;
            glyph_entries.push((c, bmp, w, h, metrics.advance_width, bx, by));
        }
        let count = glyph_entries.len() as u32;
        let cols = (count as f32).sqrt().ceil() as u32;
        let rows = (count as usize).div_ceil(cols as usize);
        let tex_w = (cols as usize) * max_w;
        let tex_h = rows * max_h;
        let tex_w = tex_w.max(1);
        let tex_h = tex_h.max(1);
        let mut alpha = vec![0u8; tex_w * tex_h];
        let mut glyphs_map = HashMap::new();
        for (i, (ch, bmp, w, h, advance, bx, by)) in glyph_entries.into_iter().enumerate() {
            let idx = i as u32;
            let row = idx / cols;
            let col = idx % cols;
            let x_offset = (col as usize) * max_w;
            let y_offset = (row as usize) * max_h;
            for yy in 0..h {
                for xx in 0..w {
                    let src = yy * w + xx;
                    let dst_x = x_offset + xx;
                    let dst_y = y_offset + yy;
                    if dst_x < tex_w && dst_y < tex_h {
                        let dst = dst_y * tex_w + dst_x;
                        alpha[dst] = bmp[src];
                    }
                }
            }
            let u0 = x_offset as f32 / tex_w as f32;
            let v0 = y_offset as f32 / tex_h as f32;
            let u1 = (x_offset + w) as f32 / tex_w as f32;
            let v1 = (y_offset + h) as f32 / tex_h as f32;
            glyphs_map.insert(
                ch,
                GlyphInfo {
                    uv_rect: [u0, v0, u1, v1],
                    size_px: [w as f32, h as f32],
                    advance,
                    bearing: [bx, by],
                },
            );
        }
        let mut rgba = Vec::with_capacity(tex_w * tex_h * 4);
        for a in alpha {
            rgba.push(255u8);
            rgba.push(255u8);
            rgba.push(255u8);
            rgba.push(a);
        }
        let raw = RawImage2d::from_raw_rgba(rgba, (tex_w as u32, tex_h as u32));
        let texture = Texture2d::with_mipmaps(display, raw, MipmapsOption::AutoGeneratedMipmaps)
            .expect("failed to create atlas texture");
        FontAtlas {
            texture,
            glyphs: glyphs_map,
            base_px_size,
            atlas_px_size: (tex_w as u32, tex_h as u32),
        }
    }
    pub fn draw_text_screen(
        &self,
        target: &mut glium::Frame,
        display: &Display<WindowSurface>,
        program: &glium::Program,
        text: &str,
        position: [f32; 2],
        scale_screen: f32,
        color: [f32; 4],
    ) {
        #[derive(Copy, Clone)]
        struct Vertex {
            position: [f32; 2],
            tex_coords: [f32; 2],
        }
        implement_vertex!(Vertex, position, tex_coords);
        let indices = NoIndices(PrimitiveType::TriangleStrip);
        let (win_w, win_h) = display.get_framebuffer_dimensions();
        let win_w = win_w as f32;
        let win_h = win_h as f32;
        let mut max_bearing_y = 0.0f32;
        for ch in text.chars() {
            if let Some(glyph) = self.glyphs.get(&ch) {
                max_bearing_y = max_bearing_y.max(glyph.bearing[1]);
            }
        }
        let baseline_y = position[1] + max_bearing_y * scale_screen;
        let mut cursor_x = position[0];
        let sampled = self
            .texture
            .sampled()
            .minify_filter(glium::uniforms::MinifySamplerFilter::LinearMipmapLinear)
            .magnify_filter(glium::uniforms::MagnifySamplerFilter::Linear);
        for ch in text.chars() {
            let g = match self.glyphs.get(&ch) {
                Some(g) => g,
                None => {
                    cursor_x += self.base_px_size * scale_screen * 0.5;
                    continue;
                }
            };
            let bearing_x = g.bearing[0] * scale_screen;
            let bearing_y = g.bearing[1] * scale_screen;
            let left = cursor_x + bearing_x;
            let top = baseline_y - bearing_y;
            let w_px = g.size_px[0] * scale_screen;
            let h_px = g.size_px[1] * scale_screen;
            let bottom = top + h_px;
            let x0 = 2.0 * left / win_w - 1.0;
            let x1 = 2.0 * (left + w_px) / win_w - 1.0;
            let y0_gl = 1.0 - 2.0 * top / win_h;
            let y1_gl = 1.0 - 2.0 * bottom / win_h;
            let verts = [
                Vertex {
                    position: [x0, y0_gl],
                    tex_coords: [g.uv_rect[0], g.uv_rect[1]],
                },
                Vertex {
                    position: [x1, y0_gl],
                    tex_coords: [g.uv_rect[2], g.uv_rect[1]],
                },
                Vertex {
                    position: [x0, y1_gl],
                    tex_coords: [g.uv_rect[0], g.uv_rect[3]],
                },
                Vertex {
                    position: [x1, y1_gl],
                    tex_coords: [g.uv_rect[2], g.uv_rect[3]],
                },
            ];
            let vb = glium::VertexBuffer::new(display, &verts).unwrap();
            let uniforms = uniform! {
                text_color: color,
                tex: sampled,
            };
            let draw_params = glium::DrawParameters {
                blend: glium::Blend::alpha_blending(),
                depth: glium::Depth {
                    test: glium::draw_parameters::DepthTest::Overwrite,
                    write: false,
                    ..Default::default()
                },
                ..Default::default()
            };
            target
                .draw(&vb, indices, program, &uniforms, &draw_params)
                .unwrap();
            cursor_x += g.advance * scale_screen;
        }
    }
    pub fn draw_text_world(
        &self,
        target: &mut glium::Frame,
        display: &Display<WindowSurface>,
        program: &glium::Program,
        text: &str,
        position: [f32; 3],
        scale_world: f32,
        color: [f32; 4],
        view: Matrix4<f32>,
        projection: Matrix4<f32>,
    ) {
        #[derive(Copy, Clone)]
        struct Vertex {
            position: [f32; 3],
            tex_coords: [f32; 2],
        }
        implement_vertex!(Vertex, position, tex_coords);
        let indices = NoIndices(PrimitiveType::TriangleStrip);
        let mut cursor_x = position[0];
        let baseline_y = position[1];
        let z = position[2];
        let sampled = self
            .texture
            .sampled()
            .minify_filter(glium::uniforms::MinifySamplerFilter::LinearMipmapLinear)
            .magnify_filter(glium::uniforms::MagnifySamplerFilter::Linear);
        for ch in text.chars() {
            let g = match self.glyphs.get(&ch) {
                Some(g) => g,
                None => {
                    cursor_x += (self.base_px_size * scale_world) * 0.5;
                    continue;
                }
            };
            let bearing_x = g.bearing[0] * scale_world;
            let bearing_y = g.bearing[1] * scale_world;
            let left = cursor_x + bearing_x;
            let top_y = baseline_y + bearing_y;
            let bottom_y = top_y - g.size_px[1] * scale_world;
            let w = g.size_px[0] * scale_world;
            let verts = [
                Vertex {
                    position: [left, top_y, z],
                    tex_coords: [g.uv_rect[0], g.uv_rect[1]],
                },
                Vertex {
                    position: [left + w, top_y, z],
                    tex_coords: [g.uv_rect[2], g.uv_rect[1]],
                },
                Vertex {
                    position: [left, bottom_y, z],
                    tex_coords: [g.uv_rect[0], g.uv_rect[3]],
                },
                Vertex {
                    position: [left + w, bottom_y, z],
                    tex_coords: [g.uv_rect[2], g.uv_rect[3]],
                },
            ];
            let vb = glium::VertexBuffer::new(display, &verts).unwrap();
            let model =
                cgmath::Matrix4::<f32>::from_translation(cgmath::vec3(0.0f32, 0.0f32, 0.0f32));
            let mvp = projection * view * model;
            let uniforms = uniform! {
                mvp: Into::<[[f32;4];4]>::into(mvp),
                text_color: color,
                tex: sampled,
            };
            let draw_params = glium::DrawParameters {
                blend: glium::Blend::alpha_blending(),
                depth: glium::Depth {
                    test: glium::draw_parameters::DepthTest::IfLess,
                    write: true,
                    ..Default::default()
                },
                ..Default::default()
            };
            target
                .draw(&vb, indices, program, &uniforms, &draw_params)
                .unwrap();
            cursor_x += g.advance * scale_world;
        }
    }
    pub fn text_size(&self, text: &str, scale: f32) -> [f32; 2] {
        let mut width = 0.0f32;
        let mut max_top = 0.0f32;
        let mut min_bottom = 0.0f32;
        for ch in text.chars() {
            match self.glyphs.get(&ch) {
                Some(g) => {
                    width += g.advance;
                    let top_y = g.bearing[1];
                    let bottom_y = top_y - g.size_px[1];
                    max_top = max_top.max(top_y);
                    min_bottom = min_bottom.min(bottom_y);
                }
                None => {
                    width += self.base_px_size * 0.5;
                }
            }
        }
        let height = (max_top - min_bottom) * scale;
        [width * scale, height]
    }
}
#[derive(Clone)]
pub struct TextBounds {
    pub width: f32,
    pub height: f32,
}
pub struct TextLabel {
    pub text: String,
    pub position: [f32; 2],
    pub scale: f32,
    pub color: [f32; 4],
    bounds: TextBounds,
}
impl TextLabel {
    pub fn new(
        font_atlas: &FontAtlas,
        text: &str,
        position: [f32; 2],
        scale: f32,
        color: [f32; 4],
    ) -> Self {
        let [width, height] = font_atlas.text_size(text, scale);
        let bounds = TextBounds { width, height };
        TextLabel {
            text: text.to_string(),
            position,
            scale,
            color,
            bounds,
        }
    }
    pub fn set_text(&mut self, font_atlas: &FontAtlas, new_text: &str) {
        let [width, height] = font_atlas.text_size(new_text, self.scale);
        self.text = new_text.to_string();
        self.bounds = TextBounds { width, height };
    }
    pub fn set_position(&mut self, new_position: [f32; 2]) {
        self.position = new_position;
    }
    pub fn set_scale(&mut self, font_atlas: &FontAtlas, new_scale: f32) {
        let [width, height] = font_atlas.text_size(&self.text, new_scale);
        self.scale = new_scale;
        self.bounds = TextBounds { width, height };
    }
    pub fn set_color(&mut self, new_color: [f32; 4]) {
        self.color = new_color;
    }
    pub fn is_mouse_hover(&self, mouse_pos: [f64; 2]) -> bool {
        let min_x = self.position[0];
        let min_y = self.position[1];
        let max_x = min_x + self.bounds.width;
        let max_y = min_y + self.bounds.height;
        mouse_pos[0] >= min_x.into()
            && mouse_pos[0] < max_x.into()
            && mouse_pos[1] >= min_y.into()
            && mouse_pos[1] < max_y.into()
    }
    pub fn draw(
        &self,
        target: &mut Frame,
        display: &Display<WindowSurface>,
        font_atlas: &FontAtlas,
        program: &Program,
    ) {
        font_atlas.draw_text_screen(
            target,
            display,
            program,
            &self.text,
            self.position,
            self.scale,
            self.color,
        );
    }
    pub fn get_bounds(&self) -> TextBounds {
        self.bounds.clone()
    }
}
