# # .cargo/config.toml
# # Глобальные настройки компилятора для проекта (локально).

# [build]
# # rustc-wrapper = "sccache"
# # Флаги для компилятора
# rustflags = [
#     "-C", "opt-level=0",           # Минимальная оптимизация для debug
#     "-C", "codegen-units=256",     # Параллелизм для debug
#     "-C", "incremental=true",      # Инкрементальная компиляция
#     "-Z", "threads=8",             # 8 потоков компиляции (настрой под свой CPU)
#     "-Z", "share-generics=y",      # Делим generics (nightly, ускоряет debug)
#     # "-Z", "thin-lto"               # Thin LTO для ускорения линковки (nightly)
# ]

# # [target.x86_64-pc-windows-msvc]
# # # Настройки для Windows (MSVC toolchain)
# # linker = "lld-link"                # Используем lld вместо link.exe
# # rustflags = [
# #     "-C", "link-arg=-fuse-ld=lld", # Указываем lld для линковки
# # ]

# [profile.release]
# # Переопределяем rustflags для release
# rustflags = [
#     "-C", "opt-level=3",           # Максимальная оптимизация
#     "-C", "codegen-units=1",       # Одна единица для оптимизации
#     "-C", "target-cpu=native",     # Оптимизация под твой CPU
#     "-C", "lto=fat",               # Полное LTO
#     "-Z", "share-generics=n",      # Отключаем разделение generics
# ]